### ISSUE TITLE
GUI TODO

### ISSUE THREAD

**Issue by covert-encryption** [covert-encryption/covert#37]
The current GUI implementation is quite rudimentary and many things need improvement. This issue is tracking tasks needing to be done:
* [x] Add QApplication, menubar and/or application icon.
* [x] Implement a *flash message* widget that can be used for showing briefly disappearing status messages inside the main window without spawning message popups.
* [x] Implement a smarter way of switching between different views within the main window
   - [x] Refactor GUI widgets/views to to separate unrelated things
* [x] Pre-decryption view, where secret keys may be loaded one by one, and passwords may be entered, until one that unlocks the data is found, triggering the next view
   - [x] Needs a version of the password widget that, unlike the existing one does not show any password hints or emoji, but that still does tab completion and works inside the main window (as opposed to popups)
* [x] Decrypted view (can be the same as the post-encryption view or very similar), where list of files and message are shown
   - [x] Display all relevant information using proper widgets and graphics
   - [x] Should have a button at bottom to extract all files to some folder
   - [ ] Show files as items supporting selection and drag&drop
* [ ] Implement a view that shows the filelist, file hash and other such details after encryption (possibly with a back button that takes one back to the new message view without clearing keys, message or attachments)
* [ ] Perform encryption and decryption in threads (avoid hanging UI, display status updates via GUI timer event)
* [ ] Perform password hashing (first stage) in threads (avoid hanging UI)
* [x] Storing file encryption key temporarily in RAM so that the data just encrypted/decrypted can be reopened without recipient keys (needs changes to covert.blockstream/cryptoheader)

Note on file list and attachments: the new message view displays attached folders as a single item but the file lists should probably be listviews/details and they need to list each file (of recursive scanning too) together with its size, as well as possibly display lines for message and padding too (following CLI UI).

**Comment by covert-encryption** [comment]
All views should use a similar layout, with logo on top left and main navigation toolbar on top, ideally also other elements in same places. The size of these static elements should be the same on each view.

**Comment by covert-encryption** [comment]
Possibly passwords to Minisign and SSH keys could also be asked for within the main window (currently implemented as popup windows via `passphrase.ask`)
